# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'College Reminder' do

  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.1'
  pod 'GoogleMaps'
  
end

target 'College ReminderTests' do

end
